version: '3'
services:
  anotai-mongodb:
    image: mongo:latest
    container_name: anotai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  anotai-rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: anotai-rabbitmq
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - :15672:15672 # communication with the web management API 
      - 5672:5672 # default communication
      - 8080:15672
    volumes:
      - /rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  
  anotai-localstack:
    image: localstack/localstack
    container_name: anotai-localstack
    environment:
      DEBUG: 1
      SERVICES: s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_DEFAULT_OUTPUT: ${AWS_DEFAULT_OUTPUT}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      EDGE_PORT: 4566
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "4572:4572" # S3 Service
      - "4576:4576" # SQS Service
      - "4566:4566" # LocalStack Gateway
    volumes:
      - /var/lib/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

volumes: 
  mongodb-data: