version: '3'
services:
  anotai-mongodb:
    image: mongo:latest
    container_name: anotai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  anotai-rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: anotai-rabbitmq
    ports: 
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - :15672:15672 # communication with the web management API 
      - 5672:5672 # default communication
      - 8080:15672
    volumes:
      - /rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER = ${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS = ${RABBITMQ_PASSWORD}
  
volumes:
  mongodb-data: